require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
    TargetRubyVersion: 3.0.3
    NewCops: enable

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'guard']

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Metrics/MethodLength:
  Exclude: 
    - 'db/migrate/*'
