require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
    TargetRubyVersion: 3.0.0
    NewCops: enable

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/simple_form.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'guard']
  Exclude:
    - 'config/environments/*'
    - 'rspec/**/*.rb'
    - 'app/admin/*.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Metrics/MethodLength:
  Exclude: 
    - 'db/migrate/*'

Rails/BulkChangeTable:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/20220909104437_create_active_storage_tables.active_storage.rb
