version: 2.1 # Use 2.1 to enable using orbs and other features.

orbs:
  ruby: circleci/ruby@1.0 
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0-node # use a tailored CircleCI docker image.
    steps:
      - checkout # pull down our git code.
      - ruby/install-deps
      - node/install-packages: 
          pkg-manager: yarn
          cache-key: "yarn.lock"

  test:
    parallelism: 3 
    docker:
      - image: cimg/ruby:3.0-node
      - image: circleci/postgres:9.5-alpine 
        environment:
          POSTGRES_USER: book_store
          POSTGRES_DB: book_store_test
          POSTGRES_PASSWORD: "book_store"
    # environment variables specific to Ruby/Rails, applied to the primary container.
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      BOOK_STORE_DATABASE_PASSWORD: "book_store"
      RAILS_ENV: test
    steps:
      - checkout 
      - ruby/install-deps 
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
