default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.bookstore.username %>
  password: <%= Rails.application.credentials.bookstore.password %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RubyBookstore_development

test:
  <<: *default
  database: RubyBookstore_test

production:
  <<: *default
  database: RubyBookstore_production
