default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: Rails.application.credentials.dig(:bookstore, :password)
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RubyBookstore_development

production:
  <<: *default
  database: RubyBookstore_production
  username: RubyBookstore
  password: <%= ENV["RUBYBOOKSTORE_DATABASE_PASSWORD"] %>
