default: &default
  adapter: postgresql
  encoding: unicode
  username: ivan
  password: admin
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RubyBookstore_development

test:
  <<: *default
  database: RubyBookstore_test

production:
  <<: *default
  database: RubyBookstore_production
